server:
  port: 9500
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /securityInfo/manage
spring:
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  application:
    name: security-info-manage
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
      enabled: true
swagger:
    enable: true
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100

