spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  #静态文件资源
  static:
    template-page-path: classpath:/templates/
    resources:
      #访问静态资源规则，可配置多个以','或'，'隔离
      - pathPatterns: /**
        #静态资源文件位置，可配置多个以','或'，'隔离
        resourceLocations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security_info?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: Ztt123#@!
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 50000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 30
      minimum-idle: 10
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9200
      repositories:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50
        min-idle: 0
        max-idle: 50
        max-wait: -1
    key-prefix: pord-

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.security.info.manage.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  global-config:
    sql-parser-cache: true
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
sign:
  verify: true

async:
  push:
   pool-size:
     core: 100
     max: 100
logging:
  file:
    path: ./log

excluded:
  pages: /securityInfo/manage/sys/login,/securityInfo/manage/sys/h5sign,/securityInfo/manage/sys/scan/login,/securityInfo/manage/sys/vx/login,/securityInfo/manage/sys/vx/login/simple,/securityInfo/manage/sys/vx/audit/status,/securityInfo/manage/dept/sync/list,/securityInfo/manage/user/sync/list

vx-business:
  corpid: ww56aa612b390c11d2
  corpsecret: B9L_KTNLvjUtrqnn6A1A0fAeN8PdDtlpMivmHZ1kd2Y
  appcorpsecret: r5cMqRKzRwFoQNzqL3usi_bI9sv3Cz-VZ3-xqU86XEM
  pccorpsecret: yIUCfWtEkRCXe3-98wZCfI7K448wGztfNiAWrGxXWoE
  appid: 1000014
  agentid: 1000016
  applets-id: wxf66d4defa7f76eb8
  applets-secret: 1fa4df7614044439f05e052aa799fdaf
  jumppage: https://security.zttgs.com:3443/security/jumpPage.html

minio:
  url: http://127.0.0.1:9000
  imgPath: https://security.zttgs.com:3443
  accessKey: zttadmin
  secretKey: ztt_123#@!

es:
  url: 127.0.0.1:9200
  index: law-file

pro:
  name: security-info-manage

ztt-4g:
  url: 122.228.42.74
  port: 1854
  address: 122.228.42.74
  user: admin
  password: Zttddjxb123
  path: https://security.zttgs.com:3443

safe-expect:
  template:
    num: 5

aliyun:
  accessKeyId: LTAI3MpFPRn4zBK5
  accessKeySecret: 9x0XLMV45km8wXkOMMQDu6e56UTeK5
  verifyCode: SMS_246160377
  signName: 中铁通轨道运营有限公司
